apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno
rendezvousIP: 192.168.4.126
additionalNTPSources:
- 192.168.4.124
hosts:
  - hostname: sno.test.local
    role: master
    interfaces:
      - name: eno1
        macAddress: 00:00:00:00:00:00
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: 00:00:00:00:00:00
          ipv4:
            enabled: true
            address:
              - ip: 192.168.4.126
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.4.1
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.4.1
            next-hop-interface: eno1
            table-id: 254
